import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Shopcart online store",
    description: "Generated by Duckmoiz",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="">
            <Header />
            <body className="font-poppins antialiased">{children}</body>
            <Footer />
        </html>
    );
}
